import type { Metadata } from 'next';
import Link from 'next/link';
import { ReactNode } from 'react';
import { ThemeProvider } from '@/components/theme-provider';
import { ModeToggle } from '@/components/ui/mode-toggle';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='antialiased m-5='>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <div className='flex gap-3 dark:gap-5'>
            <span className='dark:text-red-500'>Root</span>
            <Link href='/hello'>Hello</Link>
            <Link href='/hi'>Hi</Link>
            <Link href='/hi/night'>Hi Night</Link>
            <Link href='/parallel'>Parallel</Link>
            <Link href='/intercept'>Intercept</Link>
            <Link href='/photos'>Photos</Link>
            <ModeToggle />
          </div>

          {children}

          <hr />
          <h2>Footer</h2>
        </ThemeProvider>
      </body>
    </html>
  );
}
