services:
  localdb:
    container_name: hana7db
    image: mysql:8.0
    ports:
      - 3309:3306
    expose:
      - 3309
    environment:
      MYSQL_ROOT_PASSWORD: TestdbRoot
      MYSQL_DATABASE: testdb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    volumes:
      - ./mysql:/var/lib/mysql
