@baseUrl=http://localhost:8081


### login - success
POST {{baseUrl}}/api/subscriber/login
Content-Type: application/x-www-form-urlencoded

username = sample@gmail.com &
password = pwd00

> {%
    client.global.set("auth_token", response.body.accessToken);
%}

###
GET {{baseUrl}}/members
Authorization: Bearer {{auth_token}}

### login - failure
POST {{baseUrl}}/api/subscriber/login
Content-Type: application/x-www-form-urlencoded

username = sample@gmail.com &
password = pwd00x


### textbook
POST {{baseUrl}}/api/subscriber/login?username=sample@gmail.com&password=pwd00
#Content-Type: application/x-www-form-urlencoded
