name: ttt workflow
on:
  push:
    branches:
      - develop
jobs:
  start_pwd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: echo
        run: echo "Start Ci/CD"
      - name: ls
        run: ls -al

      - uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: grant exe to gradlew
        working-directory: spring/spring-demo
        run: chmod +x gradlew

      - name: build with gradle
        working-directory: spring/spring-demo
        run: ./gradlew clean build -x test

      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.WAS }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: scp jar to was
        run: |
          scp spring/spring-demo/build/libs/*.jar ec2-user@${{ secrets.WAS }}:/home/ec2-user/workspace/
